.include "asm/macros.inc"

.syntax unified
.section .text

@ This area is probably automatically generated by agbcc for ARM interworking.
@ TODO: Have this generated automatically.

	thumb_func_start sub_801A41C
sub_801A41C: @ 0x0801A41C
	bx pc
	nop

	.arm
_0801A420:
	b sub_80001CC

	thumb_func_start sub_801A424
sub_801A424: @ 0x0801A424
	bx pc
	nop

	.arm
_0801A428:
	b sub_80002BC

	thumb_func_start sub_801A42C
sub_801A42C: @ 0x0801A42C
	bx pc
	nop

	.arm
_0801A430:
	b sub_800076C

	thumb_func_start sub_801A434
sub_801A434: @ 0x0801A434
	bx pc
	nop

	.arm
_0801A438:
	b sub_80007A0

	thumb_func_start sub_801A43C
sub_801A43C: @ 0x0801A43C
	bx pc
	nop

	.arm
_0801A440:
	b sub_8000344

	thumb_func_start sub_801A444
sub_801A444: @ 0x0801A444
	bx pc
	nop

	.arm
_0801A448:
	b sub_8000894

	thumb_func_start sub_801A44C
sub_801A44C: @ 0x0801A44C
	bx pc
	nop

	.arm
_0801A450:
	b sub_80007E4

	thumb_func_start sub_801A454
sub_801A454: @ 0x0801A454
	bx pc
	nop

	.arm
_0801A458:
	b sub_8000808
